/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedAccountantRouteImport } from './routes/_authenticated/accountant'
import { Route as AuthenticatedAgentRouteImport } from './routes/_authenticated/agent'
import { Route as AuthenticatedBuyerRouteImport } from './routes/_authenticated/buyer'
import { Route as AuthenticatedCardsRouteImport } from './routes/_authenticated/cards'
import { Route as AuthenticatedCollectRouteImport } from './routes/_authenticated/collect'
import { Route as AuthenticatedCollectionsRouteImport } from './routes/_authenticated/collections'
import { Route as AuthenticatedFarmerRouteImport } from './routes/_authenticated/farmer'
import { Route as AuthenticatedFieldSetupRouteImport } from './routes/_authenticated/field-setup'
import { Route as AuthenticatedManagerRouteImport } from './routes/_authenticated/manager'
import { Route as AuthenticatedOwnerRouteImport } from './routes/_authenticated/owner'
import { Route as AuthenticatedTransfersRouteImport } from './routes/_authenticated/transfers'
import { Route as AuthenticatedTripRouteImport } from './routes/_authenticated/trip'
import { Route as AuthenticatedCardCodeRouteImport } from './routes/_authenticated/card.$code'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAccountantRoute = AuthenticatedAccountantRouteImport.update({
  id: '/accountant',
  path: '/accountant',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAgentRoute = AuthenticatedAgentRouteImport.update({
  id: '/agent',
  path: '/agent',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBuyerRoute = AuthenticatedBuyerRouteImport.update({
  id: '/buyer',
  path: '/buyer',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCardsRoute = AuthenticatedCardsRouteImport.update({
  id: '/cards',
  path: '/cards',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCollectRoute = AuthenticatedCollectRouteImport.update({
  id: '/collect',
  path: '/collect',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCollectionsRoute =
  AuthenticatedCollectionsRouteImport.update({
    id: '/collections',
    path: '/collections',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFarmerRoute = AuthenticatedFarmerRouteImport.update({
  id: '/farmer',
  path: '/farmer',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFieldSetupRoute = AuthenticatedFieldSetupRouteImport.update({
  id: '/field-setup',
  path: '/field-setup',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedManagerRoute = AuthenticatedManagerRouteImport.update({
  id: '/manager',
  path: '/manager',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOwnerRoute = AuthenticatedOwnerRouteImport.update({
  id: '/owner',
  path: '/owner',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTransfersRoute = AuthenticatedTransfersRouteImport.update({
  id: '/transfers',
  path: '/transfers',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTripRoute = AuthenticatedTripRouteImport.update({
  id: '/trip',
  path: '/trip',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCardCodeRoute = AuthenticatedCardCodeRouteImport.update({
  id: '/card/$code',
  path: '/card/$code',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/accountant': typeof AuthenticatedAccountantRoute
  '/agent': typeof AuthenticatedAgentRoute
  '/buyer': typeof AuthenticatedBuyerRoute
  '/cards': typeof AuthenticatedCardsRoute
  '/collect': typeof AuthenticatedCollectRoute
  '/collections': typeof AuthenticatedCollectionsRoute
  '/farmer': typeof AuthenticatedFarmerRoute
  '/field-setup': typeof AuthenticatedFieldSetupRoute
  '/manager': typeof AuthenticatedManagerRoute
  '/owner': typeof AuthenticatedOwnerRoute
  '/transfers': typeof AuthenticatedTransfersRoute
  '/trip': typeof AuthenticatedTripRoute
  '/card/$code': typeof AuthenticatedCardCodeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/accountant': typeof AuthenticatedAccountantRoute
  '/agent': typeof AuthenticatedAgentRoute
  '/buyer': typeof AuthenticatedBuyerRoute
  '/cards': typeof AuthenticatedCardsRoute
  '/collect': typeof AuthenticatedCollectRoute
  '/collections': typeof AuthenticatedCollectionsRoute
  '/farmer': typeof AuthenticatedFarmerRoute
  '/field-setup': typeof AuthenticatedFieldSetupRoute
  '/manager': typeof AuthenticatedManagerRoute
  '/owner': typeof AuthenticatedOwnerRoute
  '/transfers': typeof AuthenticatedTransfersRoute
  '/trip': typeof AuthenticatedTripRoute
  '/card/$code': typeof AuthenticatedCardCodeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/accountant': typeof AuthenticatedAccountantRoute
  '/_authenticated/agent': typeof AuthenticatedAgentRoute
  '/_authenticated/buyer': typeof AuthenticatedBuyerRoute
  '/_authenticated/cards': typeof AuthenticatedCardsRoute
  '/_authenticated/collect': typeof AuthenticatedCollectRoute
  '/_authenticated/collections': typeof AuthenticatedCollectionsRoute
  '/_authenticated/farmer': typeof AuthenticatedFarmerRoute
  '/_authenticated/field-setup': typeof AuthenticatedFieldSetupRoute
  '/_authenticated/manager': typeof AuthenticatedManagerRoute
  '/_authenticated/owner': typeof AuthenticatedOwnerRoute
  '/_authenticated/transfers': typeof AuthenticatedTransfersRoute
  '/_authenticated/trip': typeof AuthenticatedTripRoute
  '/_authenticated/card/$code': typeof AuthenticatedCardCodeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/accountant'
    | '/agent'
    | '/buyer'
    | '/cards'
    | '/collect'
    | '/collections'
    | '/farmer'
    | '/field-setup'
    | '/manager'
    | '/owner'
    | '/transfers'
    | '/trip'
    | '/card/$code'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/accountant'
    | '/agent'
    | '/buyer'
    | '/cards'
    | '/collect'
    | '/collections'
    | '/farmer'
    | '/field-setup'
    | '/manager'
    | '/owner'
    | '/transfers'
    | '/trip'
    | '/card/$code'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/accountant'
    | '/_authenticated/agent'
    | '/_authenticated/buyer'
    | '/_authenticated/cards'
    | '/_authenticated/collect'
    | '/_authenticated/collections'
    | '/_authenticated/farmer'
    | '/_authenticated/field-setup'
    | '/_authenticated/manager'
    | '/_authenticated/owner'
    | '/_authenticated/transfers'
    | '/_authenticated/trip'
    | '/_authenticated/card/$code'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/accountant': {
      id: '/_authenticated/accountant'
      path: '/accountant'
      fullPath: '/accountant'
      preLoaderRoute: typeof AuthenticatedAccountantRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/agent': {
      id: '/_authenticated/agent'
      path: '/agent'
      fullPath: '/agent'
      preLoaderRoute: typeof AuthenticatedAgentRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/buyer': {
      id: '/_authenticated/buyer'
      path: '/buyer'
      fullPath: '/buyer'
      preLoaderRoute: typeof AuthenticatedBuyerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cards': {
      id: '/_authenticated/cards'
      path: '/cards'
      fullPath: '/cards'
      preLoaderRoute: typeof AuthenticatedCardsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/collect': {
      id: '/_authenticated/collect'
      path: '/collect'
      fullPath: '/collect'
      preLoaderRoute: typeof AuthenticatedCollectRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/collections': {
      id: '/_authenticated/collections'
      path: '/collections'
      fullPath: '/collections'
      preLoaderRoute: typeof AuthenticatedCollectionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/farmer': {
      id: '/_authenticated/farmer'
      path: '/farmer'
      fullPath: '/farmer'
      preLoaderRoute: typeof AuthenticatedFarmerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/field-setup': {
      id: '/_authenticated/field-setup'
      path: '/field-setup'
      fullPath: '/field-setup'
      preLoaderRoute: typeof AuthenticatedFieldSetupRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/manager': {
      id: '/_authenticated/manager'
      path: '/manager'
      fullPath: '/manager'
      preLoaderRoute: typeof AuthenticatedManagerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/owner': {
      id: '/_authenticated/owner'
      path: '/owner'
      fullPath: '/owner'
      preLoaderRoute: typeof AuthenticatedOwnerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/transfers': {
      id: '/_authenticated/transfers'
      path: '/transfers'
      fullPath: '/transfers'
      preLoaderRoute: typeof AuthenticatedTransfersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/trip': {
      id: '/_authenticated/trip'
      path: '/trip'
      fullPath: '/trip'
      preLoaderRoute: typeof AuthenticatedTripRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/card/$code': {
      id: '/_authenticated/card/$code'
      path: '/card/$code'
      fullPath: '/card/$code'
      preLoaderRoute: typeof AuthenticatedCardCodeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAccountantRoute: typeof AuthenticatedAccountantRoute
  AuthenticatedAgentRoute: typeof AuthenticatedAgentRoute
  AuthenticatedBuyerRoute: typeof AuthenticatedBuyerRoute
  AuthenticatedCardsRoute: typeof AuthenticatedCardsRoute
  AuthenticatedCollectRoute: typeof AuthenticatedCollectRoute
  AuthenticatedCollectionsRoute: typeof AuthenticatedCollectionsRoute
  AuthenticatedFarmerRoute: typeof AuthenticatedFarmerRoute
  AuthenticatedFieldSetupRoute: typeof AuthenticatedFieldSetupRoute
  AuthenticatedManagerRoute: typeof AuthenticatedManagerRoute
  AuthenticatedOwnerRoute: typeof AuthenticatedOwnerRoute
  AuthenticatedTransfersRoute: typeof AuthenticatedTransfersRoute
  AuthenticatedTripRoute: typeof AuthenticatedTripRoute
  AuthenticatedCardCodeRoute: typeof AuthenticatedCardCodeRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAccountantRoute: AuthenticatedAccountantRoute,
  AuthenticatedAgentRoute: AuthenticatedAgentRoute,
  AuthenticatedBuyerRoute: AuthenticatedBuyerRoute,
  AuthenticatedCardsRoute: AuthenticatedCardsRoute,
  AuthenticatedCollectRoute: AuthenticatedCollectRoute,
  AuthenticatedCollectionsRoute: AuthenticatedCollectionsRoute,
  AuthenticatedFarmerRoute: AuthenticatedFarmerRoute,
  AuthenticatedFieldSetupRoute: AuthenticatedFieldSetupRoute,
  AuthenticatedManagerRoute: AuthenticatedManagerRoute,
  AuthenticatedOwnerRoute: AuthenticatedOwnerRoute,
  AuthenticatedTransfersRoute: AuthenticatedTransfersRoute,
  AuthenticatedTripRoute: AuthenticatedTripRoute,
  AuthenticatedCardCodeRoute: AuthenticatedCardCodeRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
